name       : perl-package-stash
version    : 0.37
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Package-Stash-0.37.tar.gz : 06ab05388f9130cd377c0e1d3e3bafeed6ef6a1e22104571a9e1d7bfac787b2c
license    : Artistic-2.0
component  : programming.perl
summary    : Routines for manipulating stashes
description: |
    Routines for manipulating stashes
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
