name       : perl-package-stash
version    : '0.40'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.40.tar.gz : 5a9722c6d9cb29ee133e5f7b08a5362762a0b5633ff5170642a5b0686e95e066
homepage   : https://metacpan.org/pod/Package::Stash
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Package::Stash - Routines for manipulating stashes
description: |
    Manipulating stashes (Perl's symbol tables) is occasionally necessary, but incredibly messy, and easy to get wrong. This module hides all of that behind a simple API.
builddeps  :
    - perl-cpan-meta-check
    - perl-dist-checkconflicts
    - perl-module-implementation
    - perl-test-fatal
    - perl-test-needs
    - perl-test-requires
rundeps    :
    - perl-dist-checkconflicts
    - perl-module-implementation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
